### ISSUE TITLE
Давайте исправим процесс бинаризации факторов

### ISSUE THREAD

**Issue by isaintnik** [isaintnik/ml-rank#13]
Если бить совсем по медиане, то существуют странные случаи, когда разбиение чисто по медиане даст фигню. Поэтому стоит ввести жадность по методе Игоря.

**Comment by peter-pogorelov** [comment]
Сделал первый вариант дихтомизации по принципу максимальной энтропии разбиения. https://github.com/isaintnik/ml-rank/blob/master/dichtomization.ipynb

**Comment by isaintnik** [comment]
Это сделали.
