### ISSUE TITLE
Давайте поймём размер на котором у нас t-sne таки отрабатывает

### ISSUE THREAD

**Issue by isaintnik** [isaintnik/ml-rank#2]
Там где t-sne не обучается из-за мощностей попробуем понять на какого размера сэмпле оно осиливает.

**Comment by peter-pogorelov** [comment]
Время расчета TSNT с помощью алгоритма Barnes-Hut имеет линейную зависимость от данных. Однако его проблема заключается в том, что число компонент не должно превышать 3.

**Comment by isaintnik** [comment]
А сюда вроде бы можно просто драгндропом добавить картинку ту.
