### ISSUE TITLE
Впилить hyperopt или bayesian_optimization

### ISSUE THREAD

**Issue by isaintnik** [isaintnik/ml-rank#3]
Потюнить параметры обучения с помощью hyperopt или bayesian_optimization, а то у нас сейчас ни один метод FE не дал профита по сравнению с исходными факторами.

**Comment by peter-pogorelov** [comment]
К 29.10 будет реализована оценка параметров для SVR, LightGBMRegression моделей для методов PCA / ICA. Возможно стоит аналогичным образом подбирать оптимальное число компонент. В частности, в hyperopt-sklearn сделан враппер над SVR моделью, который внутри себя еще ищет оптимальное число компонент. Например, для датасета Facebook Comment этот метод подобрал число компонент, равное 36, что очень хорошо сказалось на RMSE оценке предсказания модели, рассчитанной по CV. 

Пока что параметры подбираются только для регрессоров.
