### ISSUE TITLE
Делаем процесс ортогонализации в виде кода

### ISSUE THREAD

**Issue by isaintnik** [isaintnik/ml-rank#6]
По итогам разговора с Игорь Евгеньевичем реализуем алгоритм ортогонализации факторов.

**Comment by isaintnik** [comment]
Берём задачку классификации. Внутри между фичами используем мультиклассификатор.

**Comment by peter-pogorelov** [comment]
Запушил алгоритм. Требуется провести небольшую ревизию, поскольку я мог не до конца понять используемый подход.

**Comment by isaintnik** [comment]
Сделано.
