### ISSUE TITLE
Исправить баг с бинаризацией в коде

### ISSUE THREAD

**Issue by isaintnik** [isaintnik/ml-rank#9]
Он сейчас создаёт фичи разного размера.
И непонятно, что код будет делать, если у нас разных значений меньше, чем бинов, который мы хотим получить.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/12896646/47991159-70941980-e0fa-11e8-9c8d-0322f8cb8c90.png">

**Comment by peter-pogorelov** [comment]
Исправлено.
